```properties
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://pawjavtapmncpkenasjv.supabase.co/auth/v1/.well-known/jwks.json

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2


spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SUPABASE_JWKS_URL}

server.port=${PORT:8080}
```
